---
# roles/vcenter_snapshot/tasks/10_create_flow.yml

- name: "Görev 11: Snapshot sayısı limitini kontrol et"
  ansible.builtin.import_tasks: 11_check_snapshot_limit.yml

- name: "Görev 12: Snapshot oluştur"
  ansible.builtin.import_tasks: 12_take_snapshot.yml

- name: "Görev 13: AWX'te silme görevini zamanla"
  ansible.builtin.import_tasks: 13_create_awx_schedule.yml